[book]
title = "Sistema +2d6 SRD"
authors = ["Newton \"Tio Nitro\" Rocha"]
language = "pt-BR"
src = "src"

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
mathjax-support = true
fold = { enable = true, level = 0 }
git-repository-url = "https://github.com/nerun/sistema2d6"

[build]
build-dir = "docs"
